from dataclasses import dataclass
from typing import List
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


@dataclass
class Document:
    title: str
    text: str


DOCUMENTS = [
    Document("Payment Onboarding", "Clients can onboard payment products through treasury services. Required steps include identity checks, account verification, risk review, and configuration of payment limits."),
    Document("Foreign Exchange Payments", "Foreign currency conversion can be improved by moving FX decisioning upstream before payment execution. This reduces dependency on beneficiary banks and improves pricing transparency."),
    Document("Servicing Questions", "Common servicing requests include payment status, transaction limits, rejected transfers, beneficiary errors, and account configuration issues."),
    Document("Product Pricing", "Interest-rate and product pricing strategies can be optimized using client balance behavior, market rates, transaction frequency, and relationship value."),
]


def chunk_documents(documents: List[Document], chunk_size: int = 55):
    chunks = []
    for doc in documents:
        words = doc.text.split()
        for i in range(0, len(words), chunk_size):
            chunk = " ".join(words[i:i + chunk_size])
            chunks.append({"title": doc.title, "chunk": chunk})
    return chunks


class SimpleRAGSearch:
    def __init__(self, chunks):
        self.chunks = chunks
        self.vectorizer = TfidfVectorizer(stop_words="english")
        self.matrix = self.vectorizer.fit_transform([c["chunk"] for c in chunks])

    def retrieve(self, query: str, top_k: int = 2):
        query_vec = self.vectorizer.transform([query])
        scores = cosine_similarity(query_vec, self.matrix).flatten()
        ranked = scores.argsort()[::-1][:top_k]
        return [(self.chunks[i], scores[i]) for i in ranked]

    def answer(self, query: str):
        retrieved = self.retrieve(query)
        context = "\n".join([f"[{item['title']}] {item['chunk']}" for item, _ in retrieved])
        return f"""
Question: {query}

Retrieved Context:
{context}

Grounded Answer:
Based on the retrieved context, the best answer is that the organization can address this by using the relevant payment, pricing, servicing, or FX workflow described above. In a production RAG system, this response would be generated by an LLM using only the retrieved context.
"""


if __name__ == "__main__":
    chunks = chunk_documents(DOCUMENTS)
    rag = SimpleRAGSearch(chunks)
    questions = [
        "How can FX conversion be improved before payment execution?",
        "What data can help optimize product pricing?",
        "What are clients contacting servicing teams about?",
    ]
    for q in questions:
        print(rag.answer(q))
        print("-" * 90)
